kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: backend
    tier: app 
    purpose: Deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: 
      app: backend
      tier: app
      purpose: Deployment
  template:
    metadata:
      labels: 
        app: backend
        tier: app
        purpose: Deployment
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: 80





