
kind: Service
apiVersion: v1 
metadata:   
  name: nginx
spec: 
  type: LoadBalancer
  selector:  #labels are used as selectors
    app: frontend
    tier: app
    purpose: Deployment
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}